  version: '3.8'
  services:
    db_auth:
      container_name: name
      ports:
        - "5432:5432"
      environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin

      image: postgres:14.3-alpine
    pgadmin:
      container_name: pg_admin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
